#ifndef _P11X_EXTEND_H_
#define _P11X_EXTEND_H_

#define SM2_KEYEX_ATTRCOUNT_DEFAUL		6 //FIXME 加上CKA_LOCAL
#define SM2_KEYEX_MAX_LEN				48

#define SM2_PUBKEY_LEN_DEFAULT			64
#define SM2_PRIKEY_LEN_DEFAULT			32
#define SM2_ECDSA_MAX_LEN				128
#define SM2_SIGN_RET_DEFAULT			64
#define SM2_CRYPTO_HEAD_DEFAULT			96

#define SC_DERIVE_SM2KEYEX_S2			0
#define SC_DERIVE_KEY					0

#define SC_DERIVE_SM2_POINTMUL_1		1
#define SM2_POINTNUMBER_DEFUALT			32
#define SM2_ECCPOINT_DEFAULT			64
#define SM2_MULTKEY_LEN_DEFAULT			64

#define SC_DERIVE_SM2_POINTMUL_2		2


#define SM3_KDF_ATTRCOUNT_DEFAULT_MIN	1
#define SM3_KDF_ATTRCOUNT_DEFAULT_MAX	5



#define SC_DERIVE_SM3_KDF				2

#define SM3_EXTEND_LEN_DEFAULT			16

#define SM4_IV_LEN						16

#define SM3_DIGEST_LEN					32

#define DEFAULT_EXTEND_KEY_LEN			16
#define DEFAULT_IV_LEN					16

#define BASE_KEY_FILE_NAME				"BK"

#define MAX_KEY_LEN 1024

#endif 
